addons:
  postgresql: 9.6

dist: trusty
language: nodejs
node_js:
  - "8.9.3"
cache:
  directories:
    - "node_modules"
before_script:
  - npm i -g knex
  - npm i knex
  - psql -c 'create database qs_express;' -U postgres
  - psql -c 'create database qs_express_test;' -U postgres
script:
  - knex migrate:latest
  - npm test
